# Generated by Django 4.0.2 on 2022-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='facebook',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='deviantart',
            field=models.URLField(blank=True, help_text='Deviantart URL', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='patreon',
            field=models.URLField(blank=True, help_text='Patreon URL', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='tumblr',
            field=models.URLField(blank=True, help_text='tumblr URL', null=True),
        ),
    ]
