# Generated by Django 3.2.12 on 2022-03-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Susbcriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.CharField(help_text='Email address', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='full_name',
            field=models.CharField(help_text='First and last name', max_length=100),
        ),
    ]
